on:
  push:
    branches:
    - master
#TODO: Take of main branch
    - main
  pull_request:
    branches:
    - '**'
name: Quick Test
jobs:
  smoke-test:
    runs-on: nvme-zns
    steps:
      - name: Debug
        run: echo DEBUG

