#TODO: make sure to run on 1TB zns drives -> look at disk-select option
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * fri'
name: MTR Tests
jobs:
  mtr-tests:
    runs-on: nvme-zns
    timeout-minutes: 1440
    steps:
      - name: Clean
        run: rm -rf ${GITHUB_WORKSPACE}/*

      - name: Prepare zoned block devices
        run: |
          for i in $(seq 0 3)
          do
              DEV="ZBD$i"
              if [ ! -b "/dev/${!DEV}" ]
              then
                echo "/dev/${!DEV} is not available for zenfs-mtr!"
                exit 1
              fi
              echo deadline > /sys/block/${!DEV}/queue/scheduler
          done

      - name: Checkout percona-server
        uses: actions/checkout@v4
        with:
          repository: percona/percona-server
          ref: release-8.0.34-26
          path: percona-server
          submodules: true

      - name: Remove default zenfs
        run: rm -r percona-server/storage/rocksdb/rocksdb_plugins/zenfs

      - name: Checkout recent zenfs
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: percona-server/storage/rocksdb/rocksdb_plugins/zenfs

      - name: Build percona container image
        run: |
          podman build --cgroup-manager cgroupfs \
          -t percona-server \
          -f percona-server/storage/rocksdb/rocksdb_plugins/zenfs/.github/workflows/containerfiles/Dockerfile.percona-server \
          --build-arg LIBZBD_GIT_CHECKOUT=v2.0.4 \
          .

      - name: Run MTR RocksDB test
        id: mtrTest1
        run: |
          podman run --rm -i --device /dev/$ZBD0 \
          --volume ${GITHUB_WORKSPACE}/percona-server/storage/rocksdb/rocksdb_plugins/zenfs/.github/workflows/mtr:/scripts \
          --workdir /scripts \
          --env DEVICE0="$ZBD0" \
          percona-server \
          bash wrapper.sh bash mtr-rocksdb-test.sh
        continue-on-error: true

      - name: Run MTR RocksDB replication test
        id: mtrTest2
        run: |
          podman run --rm -i --device /dev/$ZBD0 \
          --device /dev/$ZBD1 \
          --volume ${GITHUB_WORKSPACE}/percona-server/storage/rocksdb/rocksdb_plugins/zenfs/.github/workflows/mtr:/scripts \
          --workdir /scripts \
          --env DEVICE0="$ZBD0" \
          --env DEVICE1="$ZBD1" \
          percona-server \
          bash wrapper.sh bash mtr-rocksdb-replication-test.sh
        continue-on-error: true

      - name: Run MTR RocksDB parallel test
        id: mtrTest3
        run: |
          podman run --rm -i --device /dev/$ZBD0 \
          --device /dev/$ZBD1 \
          --device /dev/$ZBD2 \
          --device /dev/$ZBD3 \
          --volume ${GITHUB_WORKSPACE}/percona-server/storage/rocksdb/rocksdb_plugins/zenfs/.github/workflows/mtr:/scripts \
          --workdir /scripts \
          --env DEVICE0="$ZBD0" \
          --env DEVICE1="$ZBD1" \
          --env DEVICE2="$ZBD2" \
          --env DEVICE3="$ZBD3" \
          percona-server \
          bash wrapper.sh bash mtr-rocksdb-parallel-test.sh
        continue-on-error: true

      - name: Run MTR RocksDB parallel replication test
        id: mtrTest4
        run: |
          podman run --rm -i --device /dev/$ZBD0 \
          --device /dev/$ZBD1 \
          --device /dev/$ZBD2 \
          --device /dev/$ZBD3 \
          --volume ${GITHUB_WORKSPACE}/percona-server/storage/rocksdb/rocksdb_plugins/zenfs/.github/workflows/mtr:/scripts \
          --workdir /scripts \
          --env DEVICE0="$ZBD0" \
          --env DEVICE1="$ZBD1" \
          --env DEVICE2="$ZBD2" \
          --env DEVICE3="$ZBD3" \
          percona-server \
          bash wrapper.sh bash mtr-rocksdb-parallel-replication-test.sh
        continue-on-error: true

      - name: Remove images
        run: podman image prune --force
        if: always()

      - name: Failure check
        if: steps.mtrTest1.outcome != 'success' || steps.mtrTest2.outcome != 'success' || steps.mtrTest3.outcome != 'success' || steps.mtrTest4.outcome != 'success'
        run: exit 1
